#:schema node_modules/wrangler/config-schema.json
name = "bondly-official"
compatibility_date = "2024-02-22"
pages_build_output_dir = "./dist"

[[d1_databases]]
binding = "DB"
database_name = "bondly-db"
database_id = "NEW_D1_ID_PROMPT" # Naya D1 banane ke baad yahan ID aayegi

[vars]
# Production Environment Variables
# Inhe dashboard se set karna best rehta hai
NODE_VERSION = "20"
