#:schema node_modules/wrangler/config-schema.json

name = "bondly-official"
compatibility_date = "2024-02-22"

[[d1_databases]]
binding = "DB"
database_name = "callhub-db"
database_id = "ff7486c4-2ecb-4247-8b67-d24a2ddb8749"

[[kv_namespaces]]
binding = "RATE_LIMIT_KV"
id = "d325c06035d44841a94a2637982062d2"
