#:schema node_modules/wrangler/config-schema.json
name = "bondly-pinkui"
compatibility_date = "2024-02-22"
pages_build_output_dir = "./dist"

[vars]
# Add your environment variables here
# VITE_SOCKET_URL = "..."
